- measures/301EnergyRatingIndexRuleset/measure.rb
- measures/301EnergyRatingIndexRuleset/measure.xml
- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
- measures/OSWtoHPXMLExport/measure.xml
- measures/OSWtoHPXMLExport/resources/301validator.rb
- resources/301validator.rb
- workflow/sample_files/valid-foundation-slab.xml
- workflow/sample_files/valid-foundation-unconditioned-basement.xml
- workflow/sample_files/valid-foundation-vented-crawlspace.xml
- workflow/sample_files/valid-hvac-air-to-air-heat-pump.xml
- workflow/sample_files/valid-hvac-boiler-elec-only.xml
- workflow/sample_files/valid-hvac-boiler-gas-only.xml
- workflow/sample_files/valid-hvac-central-ac-only.xml
- workflow/sample_files/valid-hvac-elec-resistance-only.xml
- workflow/sample_files/valid-hvac-furnace-elec-only.xml
- workflow/sample_files/valid-hvac-furnace-gas-only.xml
- workflow/sample_files/valid-hvac-ground-to-air-heat-pump.xml
- workflow/sample_files/valid-hvac-mini-split-heat-pump.xml
- workflow/sample_files/valid-hvac-none-no-fuel-access.xml
- workflow/sample_files/valid-hvac-none.xml
- workflow/sample_files/valid-hvac-room-ac-only.xml
- workflow/sample_files/valid.xml
Clean up sample files. Closes #13.
> Sample files cleanup

- measures/301EnergyRatingIndexRuleset/measure.xml
- measures/301EnergyRatingIndexRuleset/resources/301.rb
- resources/301.rb
Fix reference water heater when rated home has a HPWH.
> HPWH Reference Home

- Rakefile
- circle.yml
- workflow/energy_rating_index.rb
- workflow/sample_files/invalid.xml
- workflow/tests/energy_rating_index_test.rb
> Invalid test

- workflow/tests/energy_rating_index_test.rb
Allows running tests via the CLI. Addresses https://github.com/NREL/OpenStudio-ERI/issues/43
> Allow tests with CLI

- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
- measures/HPXMLTranslator/measure.rb
- measures/HPXMLTranslator/resources/airflow.rb
- measures/HPXMLTranslator/resources/ep_validator.rb
- measures/HPXMLTranslator/resources/hvac.rb
- measures/HPXMLTranslator/resources/hvac_sizing.rb
- measures/HPXMLTranslator/resources/unit_conversions.rb
- measures/HPXMLTranslator/resources/weather.rb
- workflow/sample_files/valid-enclosure-overhangs.xml
- workflow/sample_files/valid-hvac-boiler-gas-only.xml
- workflow/sample_files/valid-hvac-furnace-gas-only.xml
- workflow/sample_files/valid-hvac-stove-oil-only.xml
- workflow/sample_files/valid-hvac-wall-furnace-propane-only.xml
Connects electric auxiliary energy input (for fuel heating equipment) to EnergyPlus model.
> Implement EAE

- workflow/tests/energy_rating_index_test.rb
Reduce tolerance for method tests to HERS-specified value.
> Test tolerance

- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- measures/HPXMLtoOpenStudio/resources/hpxml.rb
- measures/HPXMLtoOpenStudio/resources/waterheater.rb
- workflow/energy_rating_index.rb
Replaces EnergyFactorMultiplier with TanklessCyclingDerate for clarity.
> Tankless derate

- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/hpxml_schemas/BaseElements.xsd
- measures/HPXMLtoOpenStudio/hpxml_schemas/HPXMLDataTypes.xsd
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- measures/HPXMLtoOpenStudio/resources/hpxml.rb
- measures/HPXMLtoOpenStudio/tests/valid-pv-array-1axis-backtracked.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-array-1axis.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-array-2axis.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-array-fixed-open-rack.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-module-premium.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-module-standard.xml
- measures/HPXMLtoOpenStudio/tests/valid-pv-module-thinfilm.xml.skip
- measures/HPXMLtoOpenStudio/tests/valid-pv-multiple.xml
- workflow/sample_files/valid-pv-array-1axis-backtracked.xml
- workflow/sample_files/valid-pv-array-1axis.xml
- workflow/sample_files/valid-pv-array-2axis.xml
- workflow/sample_files/valid-pv-array-fixed-open-rack.xml
- workflow/sample_files/valid-pv-module-premium.xml
- workflow/sample_files/valid-pv-module-standard.xml
- workflow/sample_files/valid-pv-module-thinfilm.xml.skip
- workflow/sample_files/valid-pv-multiple.xml
`PVSystem` elements now described by `Location` & `Tracking` instead of `ArrayType`. Updated code appropriately.
> HPXML PVSystem update

- Rakefile
- workflow/tests/NASEO_Technical_Exercises/NASEO-19.xml
Fix for NASEO-19.xml where ductless mini-split accidentally had a distribution system.
> NASEO-19.xml bugfix

- measures/301EnergyRatingIndexRuleset/resources/301.rb
- measures/301EnergyRatingIndexRuleset/tests/test_water_heating.rb
Fixes Reference Home DHW use when there's an unconditioned basement.
> Reference Home DHW bugfix

- Rakefile
- workflow/tests/RESNET_Tests/4.1_Standard_140/L322XC.xml
- workflow/tests/RESNET_Tests/4.1_Standard_140/L324XC.xml
- workflow/tests/RESNET_Tests/4.2_HERS_AutoGen_Reference_Home/04-L324.xml
- workflow/tests/RESNET_Tests/Other_HERS_AutoGen_IAD_Home/04-L324.xml
Fixes RimJoist/InteriorAdjacentTo specification in a couple test files.
> RimJoist bugfix

- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
Removes references to old FoundationVentilationRate/AtticVentilationRate elements.
> 301validator bugfix

- .circleci/config.yml
- docs/source/getting_started.rst
- measures/HPXMLtoOpenStudio/.circleci/config.yml
- measures/HPXMLtoOpenStudio/hpxml_schemas/BaseElements.xsd
~Waiting on final installers to update docs.~ Updated docs.
> Bump to OS 2.8.1 final

- Rakefile
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2b.xml
Test results were incorrectly showing zero values; now fixed.
> Fix HVAC2b test

- Rakefile
- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/hpxml_schemas/BaseElements.xsd
- measures/HPXMLtoOpenStudio/hpxml_schemas/HPXMLDataTypes.xsd
- measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- measures/HPXMLtoOpenStudio/resources/waterheater.rb
- measures/HPXMLtoOpenStudio/tests/base-dhw-combi-tankless-outside.xml
- measures/HPXMLtoOpenStudio/tests/base-dhw-indirect-outside.xml
- measures/HPXMLtoOpenStudio/tests/base-dhw-tank-gas-outside.xml
- measures/HPXMLtoOpenStudio/tests/base-dhw-tank-heat-pump-outside.xml
- measures/HPXMLtoOpenStudio/tests/base-dhw-tankless-electric-outside.xml
The `WaterHeatingSystem/Location` can now be set to "other exterior".
> Allow water heaters to be located outside

- Rakefile
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
- measures/HPXMLtoOpenStudio/tests/base-hvac-central-ac-plus-air-to-air-heat-pump-heating.xml
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
- measures/HPXMLtoOpenStudio/tests/hvac_autosizing/base-hvac-central-ac-plus-air-to-air-heat-pump-heating-autosize.xml
For sizing heat pumps, implements logic for using max(heat, cool) load. Also a bugfix for when FractionHeatLoadServed and FractionCoolLoadServed are different (e.g., ERI Reference Home).
> Heat Pump sizing updates

- .gitignore
- docs/source/testing_framework.rst
- workflow/tests/energy_rating_index_test.rb
Saves all simulation/HPXML/etc. files generated from running tests to the `workflow/tests/test_files` directory.
> Save test files

- .codecov.yml
- codecov.yml
Exclude HPXMLtoOpenStudio measure from codecov; already covered by OpenStudio-HPXML repo.
> Code coverage

- docs/source/getting_started.rst
- docs/source/software_connection.rst
Add more description of outputs to documentation (and discourage reading of raw E+ output files). Misc cleanup.
> Documentation - Outputs

- Rakefile
- docs/source/getting_started.rst
- workflow/energy_rating_index.rb
Fix version; add rake task to automate version bump.
> Versioning

- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
Fix FoundationWall reference in EPvalidator.rb.
> EPvalidator fix for FoundationWall

- workflow/tests/energy_rating_index_test.rb
Allows tests to be run in parallel without clobbering each other on the filesystem.
> Parallel tests

- Rakefile
- workflow/tests/RESNET_Tests/4.1_Standard_140/L322XC.xml
- workflow/tests/RESNET_Tests/4.1_Standard_140/L324XC.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3a.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3b.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3c.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3d.xml
Fixes the infiltration rate in the conditioned basement 140 tests per Table 7-39 Note 5.
> Fix 140 L322/L324 infiltration

- Rakefile
- workflow/tests/RESNET_Tests/4.2_HERS_AutoGen_Reference_Home/04-L324.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3a.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3b.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3c.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3d.xml
- workflow/tests/RESNET_Tests/Other_HERS_AutoGen_IAD_Home/04-L324.xml
Fixes a few more test files. Should have no impact on test results.
> Fix 140 L322/L324 infiltration, part 2

- measures/301EnergyRatingIndexRuleset/resources/301validator.rb
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- measures/HPXMLtoOpenStudio/resources/airflow.rb
- measures/HPXMLtoOpenStudio/tests/base-enclosure-beds-1.xml
- measures/HPXMLtoOpenStudio/tests/base-enclosure-beds-2.xml
- measures/HPXMLtoOpenStudio/tests/base-enclosure-beds-4.xml
- measures/HPXMLtoOpenStudio/tests/base-enclosure-beds-5.xml
- measures/HPXMLtoOpenStudio/tests/base-location-baltimore-md.xml
- measures/HPXMLtoOpenStudio/tests/base-location-dallas-tx.xml
- measures/HPXMLtoOpenStudio/tests/base-location-duluth-mn.xml
- measures/HPXMLtoOpenStudio/tests/base-location-miami-fl.xml
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
- workflow/sample_files/base-enclosure-beds-1.xml
- workflow/sample_files/base-enclosure-beds-2.xml
- workflow/sample_files/base-enclosure-beds-4.xml
- workflow/sample_files/base-enclosure-beds-5.xml
- workflow/sample_files/base-location-baltimore-md.xml
- workflow/sample_files/base-location-dallas-tx.xml
- workflow/sample_files/base-location-duluth-mn.xml
- workflow/sample_files/base-location-miami-fl.xml
Various small items:
- Fixes possible "Unable to calculate a construction ... using the provided assembly R-value" errors
- Removes redundant weather processing (runtime improvement)
- Fixes minor validator bug for AirInfiltrationMeasurement
- Adds more sample files
> Latest OS-HPXML

- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
Zero out view factors between conditioned basement surfaces and living space surfaces, now that we have a single conditioned thermal zone.
> Improve conditioned basement radiation heat transfer

- Rakefile
- measures/301EnergyRatingIndexRuleset/resources/301.rb
- measures/301EnergyRatingIndexRuleset/tests/test_hvac.rb
- workflow/sample_files/base-hvac-setpoints.xml
Fix for setpoints specified in the HPXML file being maintained in the Rated Home. Added test. HPXML files without setpoints specified are unaffected.
> Setpoints fix

- Rakefile
- measures/301EnergyRatingIndexRuleset/resources/301.rb
- workflow/sample_files/base-foundation-unconditioned-basement-assembly-r.xml
Fixed possible error "can't convert nil into Float" for the Reference Home. Added test file.
> Bugfix for error "can't convert nil into Float"

- measures/HPXMLtoOpenStudio/resources/waterheater.rb
Significantly speeds up simulations with heat pump water heaters.
> HPWH runtime performance

- measures/HPXMLtoOpenStudio/resources/waterheater.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
Improves controls for combi systems to mimic the setpoint and deadband controls used by other water heating systems.
> Combi boiler model improvements

- measures/301EnergyRatingIndexRuleset/resources/301.rb
- workflow/tests/energy_rating_index_test.rb
Ensure wall surfaces attached to basement, unvented crawl, etc. are removed.
> IAD configuration bugfix

- measures/301EnergyRatingIndexRuleset/resources/301.rb
Ensure wall surfaces attached to basement, unvented crawl, etc. are removed.
> IAD configuration bugfix, take 2

- measures/HPXMLtoOpenStudio/resources/constructions.rb
Improves runtime, particularly for complex buildings.
> Improve runtime

- Rakefile
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/airflow.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
- workflow/tests/energy_rating_index_test.rb
Fix zero mechanical ventilation energy use for CFIS systems set to run 24 hrs/day.
> Bugfix for CFIS running 24 hrs/day

- workflow/tests/energy_rating_index_test.rb
Reduces number of simulations for Reference/IAD Auto-Generation tests.
> Ref/IAD AutoGen tests

- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/hvac.rb
Fix for ceiling fans running year-round instead of only during certain months.
> Ceiling fans operation bugfix

- measures/301EnergyRatingIndexRuleset/resources/301.rb
- measures/301EnergyRatingIndexRuleset/tests/test_mechanical_ventilation.rb
Bugfix for Reference Home mechanical ventilation when infiltration is entered using CFM50. Added test.
> Reference Home mech vent bugfix

- measures/HPXMLtoOpenStudio/resources/waterheater.rb
- workflow/energy_rating_index.rb
Renames an output variable to prevent SketchUp import errors.
> Prevent SketchUp import errors

- measures/HPXMLtoOpenStudio/measure.rb
- workflow/energy_rating_index.rb
> Disaggregates other fuels into oil and propane.

- docs/source/outputs.rst
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/hotwater_appliances.rb
- measures/HPXMLtoOpenStudio/resources/unit_conversions.rb
- workflow/energy_rating_index.rb
Changes units for peak load in the output CSVs from W to kBtu.
> Change peak load units

- measures/301EnergyRatingIndexRuleset/resources/301.rb
Adjusts the recovery efficiency (RE) of the Reference Home water heater for consistency with other software tools.
> Reference Home water heater

- measures/HPXMLtoOpenStudio/measure.rb
Adds radiation heat transfer terms for surface and equipment objects. Fixes skylight solar gains.
> Component loads, take 2

- measures/HPXMLtoOpenStudio/measure.rb
Bugfix for possibility of infiltration and mechanical ventilation being wrong.
> Component loads bugfix

- Rakefile
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/hpxml.rb
- measures/HPXMLtoOpenStudio/resources/hvac.rb
- measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3a.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3b.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3c.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3d.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3e.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3f.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3g.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3h.xml
- workflow/tests/energy_rating_index_test.rb
Implements HERS DSE tests using updated criteria based on EnergyPlus seasonal duct zone temperatures and ASHRAE 152 calculations. Forces heating/cooling airflow rates of 360 cfm/ton per Pub 002 to pass the tests.
> DSE test criteria

- Rakefile
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2c.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2d.xml
Small bugfix for HVAC2c.xml and HVAC2d.xml.
> HVAC tests bugfix

- measures/301EnergyRatingIndexRuleset/resources/301.rb
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/hpxml.rb
- measures/HPXMLtoOpenStudio/resources/unit_conversions.rb
- measures/HPXMLtoOpenStudio/resources/waterheater.rb
- measures/HPXMLtoOpenStudio/resources/xmlhelper.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
Reduces parsing of HPXML file as appropriate. Faster unit conversions.
> Performance improvements

- measures/301EnergyRatingIndexRuleset/resources/301.rb
- workflow/energy_rating_index.rb
> Remove uses of splat operator

- docs/source/outputs.rst
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
- workflow/energy_rating_index.rb
Removes "setpoint change" component from component loads; load attributed to other components. Improved handling of partial load hours.
> Removes setpoint change from component loads

- measures/HPXMLtoOpenStudio/resources/airflow.rb
- measures/HPXMLtoOpenStudio/resources/geometry.rb
- measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
Reduces unmet heating/cooling loads in, e.g., the ERI Reference Home.
> Fixes HVAC sizing when the house has a conditioned basement

- measures/HPXMLtoOpenStudio/.gitignore
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/airflow.rb
- measures/HPXMLtoOpenStudio/tests/base-hvac-undersized.xml
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
- workflow/energy_rating_index.rb
Improvements to return duct losses model. Return duct losses are now included in component load reporting.
> Duct model improvements

- workflow/design.rb
- workflow/tests/energy_rating_index_test.rb
Exclude LCC objects, add FT errors/warnings.
> Minor stuff

- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/hvac.rb
- measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
- measures/HPXMLtoOpenStudio/resources/run_simulation.rb
- measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb
Fixes possible HVAC sizing bug for GSHPs.
> Hvac sizing fix

- measures/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
- measures/HPXMLtoOpenStudio/Rakefile
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/constructions.rb
- measures/HPXMLtoOpenStudio/tests/base-foundation-conditioned-basement-slab-insulation.xml
- measures/HPXMLtoOpenStudio/tests/base-foundation-unconditioned-basement-slab-insulation.xml
- workflow/sample_files/base-foundation-conditioned-basement-slab-insulation.xml
Fix for basement slab insulation not being used. Basement wall insulation and slab-on-grade insulation are not impacted. Added test file.
> Basement slab insulation bugfix

- workflow/design.rb
Bugfix when trying to run simulations on a different drive (either local or remote network).
> Bugfix for running on a different drive

- measures/301EnergyRatingIndexRuleset/measure.rb
- measures/HPXMLtoOpenStudio/measure.rb
- measures/HPXMLtoOpenStudio/resources/meta_measure.rb
> Some REXML cleanup.

- measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
- workflow/tests/energy_rating_index_test.rb
Bugfix for HVAC sizing error when latitude is exactly 64 (Big Delta, Alaska).
> HVAC sizing error bugfix

- hpxml-measures/HPXMLtoOpenStudio/measure.rb
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
- hpxml-measures/docs/source/hpxml_to_openstudio.rst
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/tests/base-dhw-temperature.xml
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_water_heating.rb
- tasks.rb
Adds 301 hot water temperatures to ERI____Home.xml files for transparency.
> Adds hot water temperature to HPXMLs

- LICENSE.md
- hpxml-measures/HPXMLtoOpenStudio/measure.rb
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/tests/base-foundation-walkout-basement.xml
- hpxml-measures/workflow/tests/hpxml_translator_test.rb
- workflow/sample_files/base-foundation-walkout-basement.xml
Fixes view factors when foundation walls adjacent to a conditioned basement have a window/door. Results in small changes to heating/cooling energy.
> Bugfix for windows/doors on conditioned basement walls

- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
Bugfix for conversion of nACH to SLA. Affects buildings with below-grade stories, no mechanical ventilation system, and low infiltration rates.
> nACH to SLA bugfix

- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_misc.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_water_heating.rb
- workflow/tests/energy_rating_index_test.rb
Adds more values to the ERI___Home.xml files. 
- `WaterHeatingSystem`: `PerformanceAdjustment` and `UsesDesuperheater`
- `PlugLoad`: `Load[Units="kWh/year"]/Value`, `extension/FracSensible`, and `extension/FracLatent`.
> Adds more values to the ERI___Home.xml files

- rulesets/301EnergyRatingIndexRuleset/measure.rb
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/tests/test_appliances.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_hvac.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_lighting.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_misc.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_ventilation.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_water_heating.rb
- workflow/tests/energy_rating_index_test.rb
Replacing more direct REXML calls with HPXML class calls
> Purge REXML

- docs/source/software_connection.rst
- hpxml-measures/HPXMLtoOpenStudio/measure.rb
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/airflow.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/waterheater.rb
- hpxml-measures/docs/source/hpxml_to_openstudio.rst
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/sample_files/base-foundation-walkout-basement.xml
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- workflow/sample_files/base-foundation-walkout-basement.xml
Improves inferred infiltration height for conditioned basements (including walkout basements).
> Improves inferred infiltration height

- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/hvac.rb
Changes heat pump defrost control from OnDemand to Timed.
> HP defrost control

- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_ventilation.rb
Adds infiltration height and Aext to the HPXML files for debugging purposes. Also fixes IAD Aext value.
> Infiltration outputs

- hpxml-measures/HPXMLtoOpenStudio/measure.rb
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/hotwater_appliances.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml_defaults.rb
- hpxml-measures/docs/source/hpxml_to_openstudio.rst
- rulesets/301EnergyRatingIndexRuleset/tests/test_appliances.rb
Adds appliance error-checking for negative calculated energy use or hot water use.
> Appliance error-checking

- tasks.rb
- workflow/design.rb
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC1a.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC1b.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2a.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2b.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2c.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2d.xml
- workflow/tests/RESNET_Tests/4.4_HVAC/HVAC2e.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3a.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3b.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3c.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3d.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3e.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3f.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3g.xml
- workflow/tests/RESNET_Tests/4.5_DSE/HVAC3h.xml
- workflow/tests/energy_rating_index_test.rb
Update interim acceptance criteria for ASHRAE 40, HVAC, and DSE tests. Minor cleanup for test files.
> Update acceptance criteria

- docs/source/software_connection.rst
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/resources/301.rb
- rulesets/301EnergyRatingIndexRuleset/resources/301validator.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_appliances.rb
- tasks.rb
- workflow/sample_files/base-appliances-none.xml
Allow a rated home without a refrigerator, dishwasher, range/oven, clothes washer, and/or clothes dryer.
> No appliances

- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
- hpxml-measures/HPXMLtoOpenStudio/resources/xmlhelper.rb
- hpxml-measures/HPXMLtoOpenStudio/tests/test_defaults.rb
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/sample_files/base-enclosure-other-heated-space.xml
- rulesets/301EnergyRatingIndexRuleset/measure.xml
- rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
- workflow/sample_files/base-enclosure-other-heated-space.xml
Treat other heated space as unconditioned space for determination of thermal boundary surfaces.
> Other heated space

- workflow/tests/energy_rating_index_test.rb
> Update test ranges per latest SCC proposed values

- Gemfile
- hpxml-measures/Gemfile
- hpxml-measures/HPXMLtoOpenStudio/measure.rb
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/meta_measure.rb
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/sample_files/base-foundation-basement-garage.xml
- hpxml-measures/workflow/tests/hpxml_translator_test.rb
- workflow/sample_files/base-foundation-basement-garage.xml
> Bugfix for possible FT "surface construction conflicts" errors

- .github/pull_request_template.md
- Changelog.md
Adds a Changelog.md, to be updated with each Pull Request.
> Adds Changelog.md

- Gemfile
- hpxml-measures/Gemfile
- hpxml-measures/Gemfile.lock
- hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.xml
- hpxml-measures/HPXMLtoOpenStudio/tests/test_validation.rb
- rulesets/301EnergyRatingIndexRuleset/tests/test_validation.rb
> Add schematron test

- hpxml-measures/HPXMLtoOpenStudio/resources/airflow.rb
Apply constant attic ventilation for ASHRAE 140 cases if vented attics are described using SLA instead of ACHnatural.
> ASHRAE 140 attic ventilation

- Changelog.md
- hpxml-measures/Changelog.md
- hpxml-measures/HPXMLtoOpenStudio/measure.xml
- hpxml-measures/HPXMLtoOpenStudio/resources/hvac.rb
- hpxml-measures/tasks.rb
- hpxml-measures/workflow/sample_files/invalid_files/hvac-shared-negative-seer-eq.xml
- hpxml-measures/workflow/tests/hpxml_translator_test.rb
Adds error-checking for negative SEEReq results for shared cooling systems.
> Negative SEEReq error-checking

- Changelog.md
- workflow/energy_rating_index.rb
> Bump to v1.1.1

- .github/workflows/config.yml
> Prove #533

- .github/workflows/config.yml
> Update CI config

- tasks.rb
- workflow/tests/EPA_Tests/MF_National_1.1/CZ6_VT_gas_ground_corner_cond_bsmt.xml
- workflow/tests/EPA_Tests/SF_National_3.0/CZ2_FL_gas_slab.xml
- workflow/tests/EPA_Tests/SF_National_3.0/CZ4_MO_gas_vented_crawl.xml
- workflow/tests/EPA_Tests/SF_National_3.0/CZ6_VT_elec_cond_bsmt.xml
- workflow/tests/EPA_Tests/SF_National_3.1/CZ2_FL_elec_slab.xml
- workflow/tests/EPA_Tests/SF_National_3.1/CZ4_MO_elec_vented_crawl.xml
- workflow/tests/EPA_Tests/SF_National_3.1/CZ6_VT_gas_cond_bsmt.xml
- workflow/tests/base_results/EPA_Tests.csv
Geometry-related updates to EPA test files.
> Update EPA test files

- docs/source/workflow_inputs.rst
Just a textual change correcting the path to the HPXML.xsd file
> Correct path to HPXML.xsd

- tasks.rb
- workflow/tests/EPA_Tests/MF_National_1.0/MFNCv1_CZ2_FL_gas_ground_corner_slab.xml
- workflow/tests/EPA_Tests/MF_National_1.0/MFNCv1_CZ4_MO_gas_top_corner.xml
- workflow/tests/EPA_Tests/MF_National_1.0/MFNCv1_CZ6_VT_elec_middle_interior.xml
- workflow/tests/EPA_Tests/MF_National_1.1/MFNCv11_CZ2_FL_elec_top_corner.xml
- workflow/tests/EPA_Tests/MF_National_1.1/MFNCv11_CZ4_MO_elec_ground_corner_vented_crawl.xml
- workflow/tests/EPA_Tests/MF_National_1.1/MFNCv11_CZ6_VT_gas_ground_corner_cond_bsmt.xml
- workflow/tests/base_results/EPA_Tests.csv
Small fixes for EPA test files.
> Small fixes for EPA test files

- docs/source/workflow_inputs.rst
- docs/source/workflow_outputs.rst
Clarifies documentation with respect to Aext air leakage reduction factor.
> Clarify Aext in documentation

- workflow/energy_rating_index.rb
- workflow/tests/energy_rating_index_test.rb
- workflow/tests/util.rb
> Avoid extra CO2e run when possible

- .github/workflows/config.yml
- docs/source/conf.py
- docs/source/workflow_outputs.rst
Small update to docs. Treat warnings as errors.
> Docs update

- rulesets/tests/test_es_zerh_hvac.rb
> Check ES ZERH HVAC tests

- rulesets/tests/test_appliances.rb
- rulesets/tests/test_enclosure.rb
- rulesets/tests/test_es_zerh_appliances.rb
- rulesets/tests/test_es_zerh_enclosure.rb
- rulesets/tests/test_es_zerh_generator.rb
- rulesets/tests/test_es_zerh_hvac.rb
- rulesets/tests/test_es_zerh_lighting.rb
- rulesets/tests/test_es_zerh_misc.rb
- rulesets/tests/test_es_zerh_pv_batteries.rb
- rulesets/tests/test_es_zerh_ventilation.rb
- rulesets/tests/test_es_zerh_water_heating.rb
- rulesets/tests/test_generator.rb
- rulesets/tests/test_hvac.rb
- rulesets/tests/test_lighting.rb
- rulesets/tests/test_misc.rb
- rulesets/tests/test_pv_batteries.rb
- rulesets/tests/test_validation.rb
- rulesets/tests/test_ventilation.rb
- rulesets/tests/test_water_heating.rb
> Address minitest release change that causes CI errors

- docs/source/workflow_inputs.rst
Fix docs formatting, which [broke because of sphinx_rtd_theme changes](https://github.com/readthedocs/sphinx_rtd_theme/issues/1472).
> Fix docs formatting

- Changelog.md
- rulesets/main.rb
> Backport emissions lookup bugfix

- workflow/energy_rating_index.rb
Fulfill requirements in newer HERS diagnostic output schema version.
> HERS diagnostic required fields
