measures/301EnergyRatingIndexRuleset/validate.rb

I thought this would be useful to share. It displays use case and schema validation errors for an hpxml file supplied on the command line.

Add utility for just validating an HPXML file.

---

workflow/design.rb
workflow/energy_rating_index.rb
workflow/tests/energy_rating_index_test.rb

Working directory

---

workflow/design.rb
workflow/energy_rating_index.rb

Adds an optional `-o` or `--output-dir` argument to specify where all the outputs end up. Closes #183.

Output dir argument

---

measures/301EnergyRatingIndexRuleset/resources/301.rb
workflow/energy_rating_index.rb

Adds a `--version` argument for the OpenStudio-ERI workflow.

Add Version argument

---

Rakefile
measures/301EnergyRatingIndexRuleset/resources/301.rb
measures/301EnergyRatingIndexRuleset/tests/test_mechanical_ventilation.rb
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-01.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-02.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-03.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-04.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-05.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-06.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AD-HW-07.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-01.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-02.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-03.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-04.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-05.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-06.xml
workflow/tests/RESNET_Tests/4.6_Hot_Water/L100AM-HW-07.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AD-HW-01.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AD-HW-02.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AD-HW-03.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AM-HW-01.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AM-HW-02.xml
workflow/tests/RESNET_Tests/Other_Hot_Water_PreAddendumA/L100AM-HW-03.xml
workflow/tests/energy_rating_index_test.rb

Adds a workaround to ensure the eRatio check for Reference Home Auto-Generation tests doesn't fail due to changing mechanical ventilation fan power in the Reference of the Reference Home. Similar workarounds appear to be implemented by HERS accredited software tools, as the tests cannot otherwise be passed as written.
Also fixes missing mechanical ventilation airflow in the Reference Home when the Rated Home has no mechanical ventilation. Updated unit test.

Pass Reference Home Auto-Generation tests

---

measures/301EnergyRatingIndexRuleset/resources/301.rb
measures/301EnergyRatingIndexRuleset/tests/test_appliances.rb
measures/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
measures/301EnergyRatingIndexRuleset/tests/test_hvac.rb
measures/301EnergyRatingIndexRuleset/tests/test_lighting.rb
measures/301EnergyRatingIndexRuleset/tests/test_mechanical_ventilation.rb
measures/301EnergyRatingIndexRuleset/tests/test_misc.rb
measures/301EnergyRatingIndexRuleset/tests/test_water_heating.rb

Updates the 301 ruleset for the Rated Home:
Also adds/updates unit tests.

Rated Home air exchange rate

---

workflow/energy_rating_index.rb

Only calculates HVAC/WH loads for Reference designs, so as not to accidentally use the calculations for other designs. Simplifies the use of the DSE in the RUEL calculation.
Also adds comments clarifying under which situations (e.g., HVAC types, designs) the HVAC/WH loads are calculated.

Improve REUL calc

---

docs/source/getting_started.rst
docs/source/software_connection.rst

Clarifies DWHR documentation given EnergyGauge documentation. Addresses the scenario where there are more than 2 showers in the home and exactly 2 are connected to the DWHR. (301 language doesn't seem to address it.)

DWHR documentation

---

docs/source/outputs.rst

Clarify that the ERI_Results.csv and ERI_Worksheet.csv files can have multiple values for some outputs if there are multiple heating, cooling, or hot water systems.

Clarify outputs in docs

---

workflow/energy_rating_index.rb

Prevent possibility of different line endings, resulting in an error, when trying to use custom weather files.

Custom weather bugfix

---

measures/HPXMLtoOpenStudio/measure.rb
measures/HPXMLtoOpenStudio/resources/airflow.rb
measures/HPXMLtoOpenStudio/tests/hpxml_translator_test.rb

Model balanced mech vent (i.e., without recovery) without using the ERV object.
Also includes a bugfix for sequential load fraction for some HVAC combinations.

Balanced mech vent

---

Rakefile
measures/HPXMLtoOpenStudio/Rakefile
measures/HPXMLtoOpenStudio/measure.rb
measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
measures/HPXMLtoOpenStudio/resources/hpxml.rb
measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb
measures/HPXMLtoOpenStudio/tests/base-appliances-refrigerator-adjusted.xml

Prevent E+ simulation error due to near zero autosized heating/cooling airflow rate. Can occur for, e.g., weather files of the Virgin Islands where the 99% heating design temperate > 70 F.

Prevent E+ HVAC simulation error

---

measures/HPXMLtoOpenStudio/resources/hvac.rb

Fixes a possible error: "Electric category end uses ... do not sum to total"
When disaggregrating fan energy (or pump energy) into heating and cooling, the disaggregated values sometimes did not sum to the total. This was because we were not incorporating the heat pump supplemental coils for detecting if a given timestep was heating (vs cooling).

Fix possible error: "Electric category end uses ... do not sum to total"

---

workflow/design.rb
workflow/energy_rating_index.rb

Use `FuelOil#1:Facility` and `Propane:Facility` meters for hourly output to simplify code. Not sure why I previously thought they didn't exist...

Simplify hourly output querying

---

workflow/design.rb
workflow/energy_rating_index.rb

Increase precision of outputs by using Output Meters instead of ABUPS report. Previously we were reading E+ outputs that were rounded to 0.01 GJ.

Increase output precision

---

measures/301EnergyRatingIndexRuleset/resources/301.rb
measures/301EnergyRatingIndexRuleset/tests/test_enclosure.rb

Fixes Reference Home walls/roofs/rimjoists not correctly distinguishing between thermal boundary surfaces and _exterior_ thermal boundary surfaces in the logic. Updated test.

Reference Home surfaces configuration bugfix

---

measures/HPXMLtoOpenStudio/measure.rb

Prevent possibility of tiny slivers of rigid insulation on foundation walls.

Foundation wall insulation

---

measures/301EnergyRatingIndexRuleset/resources/301validator.rb
measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
workflow/tests/energy_rating_index_test.rb

Detect and report duplicate SystemIdentifier IDs, as they can result in unpredictable behavior. SystemIdentifier IDs are supposed to be unique per the HPXML schema.

Detect duplicate IDs

---

measures/301EnergyRatingIndexRuleset/resources/301.rb
measures/301EnergyRatingIndexRuleset/tests/test_enclosure.rb

Set Reference Home uninsulated R-values to the minimum of our assumed value and the entered value. This can help to eliminate differences between the Rated/Reference Homes for uninsulated surfaces.

Reference Home uninsulated R-values

---

workflow/energy_rating_index.rb
workflow/tests/energy_rating_index_test.rb

Fixes the --cache-weather command and adds a test so that it doesn't break again.

Fix the --cache-weather command

---

hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/SimulationOutputReport/measure.rb
hpxml-measures/SimulationOutputReport/measure.xml
hpxml-measures/tasks.rb
hpxml-measures/workflow/run_simulation.rb
hpxml-measures/workflow/sample_files/hvac_multiple/base-hvac-boiler-gas-only-x3.xml

Fixes a simulation error when `FractionHeatLoadServed` or `FractionCoolLoadServed` sum to slightly greater than 1. 
The simulation was already successful if they sum to slightly less than 1. And `FractionDHWLoadServed` already works in both situations.

Allow small tolerance for hvac load fractions

---

docs/source/software_connection.rst

Clarifies in the documentation how Addenda D & L interact when, e.g., `Version2014ADEGL` is used.

Clarify Addenda D & L interaction

---

docs/source/outputs.rst
hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.rb
hpxml-measures/HPXMLtoOpenStudio/resources/constants.rb
hpxml-measures/HPXMLtoOpenStudio/resources/constructions.rb
hpxml-measures/HPXMLtoOpenStudio/resources/hotwater_appliances.rb
hpxml-measures/HPXMLtoOpenStudio/resources/waterheater.rb
hpxml-measures/SimulationOutputReport/measure.rb
hpxml-measures/SimulationOutputReport/measure.xml
hpxml-measures/SimulationOutputReport/resources/constants.rb
hpxml-measures/SimulationOutputReport/tests/output_report_test.rb
hpxml-measures/docs/source/hpxml_to_openstudio.rst
hpxml-measures/tasks.rb
hpxml-measures/workflow/run_simulation.rb
hpxml-measures/workflow/sample_files/base-misc-defaults2.xml
hpxml-measures/workflow/template.osw
hpxml-measures/workflow/tests/hpxml_translator_test.rb
rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
tasks.rb
workflow/design.rb
workflow/energy_rating_index.rb
workflow/tests/energy_rating_index_test.rb

Adds hot water outputs (gallons), disaggregated by end use, to annual output. Also available for timeseries outputs. GPD values added to DHW test results.

Hot water outputs

---

rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb

When configuring the Reference Home, preserve the distribution systems from the Rated Home when possible. Results in the Reference Home using the same W/cfm (derived from EAE) for heating/cooling when there is an AC/furnace.

Reference HVAC fan

---

rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
rulesets/301EnergyRatingIndexRuleset/tests/test_appliances.rb

Preserve the Rated Home appliance locations in the Reference Home.

Reference Home appliance locations

---

hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb

Exclude surfaces between conditioned space and Unrated Heated Space from Table 4.2.2(2) insulation values.

Unrated Heated Space Ref home R-value

---

docs/source/software_connection.rst
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/base-foundation-multiple.xml
hpxml-measures/workflow/sample_files/base-foundation-unconditioned-basement-above-grade.xml
hpxml-measures/workflow/sample_files/base-foundation-unconditioned-basement-assembly-r.xml
hpxml-measures/workflow/sample_files/base-foundation-unconditioned-basement-wall-insulation.xml
hpxml-measures/workflow/sample_files/base-foundation-unconditioned-basement.xml
hpxml-measures/workflow/sample_files/invalid_files/enclosure-basement-missing-exterior-foundation-wall.xml
hpxml-measures/workflow/sample_files/invalid_files/enclosure-basement-missing-slab.xml
rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
workflow/sample_files/base-foundation-multiple.xml
workflow/sample_files/base-foundation-unconditioned-basement-above-grade.xml
workflow/sample_files/base-foundation-unconditioned-basement-assembly-r.xml
workflow/sample_files/base-foundation-unconditioned-basement-wall-insulation.xml
workflow/sample_files/base-foundation-unconditioned-basement.xml

The Reference Home is now configured with insulation at the unconditioned basement ceiling, rather than preserving the location of the Rated Home's insulation. The ``ThermalBoundary`` input is no longer used.

Reference Home - basements

---

hpxml-measures/HPXMLtoOpenStudio/tests/test_defaults.rb
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/base-lighting-ceiling-fans.xml
rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
rulesets/301EnergyRatingIndexRuleset/tests/test_hvac.rb
rulesets/301EnergyRatingIndexRuleset/tests/test_lighting.rb
workflow/sample_files/base-lighting-ceiling-fans.xml

Bugfix for how ceiling fans are configured for 301-2019. Unlike 301-2014, there should now be no ceiling fans in the Rated/Reference Homes when the number of ceiling fans < Nbr+1.

301-2019 ceiling fan bugfix

---

rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
rulesets/301EnergyRatingIndexRuleset/tests/test_ventilation.rb

Updates 301 ruleset to increase the ventilation hours in operation first, if possible, to meet Qfan requirement, before increasing the airflow rate.

Mech vent hours in operation

---

docs/source/outputs.rst
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
hpxml-measures/HPXMLtoOpenStudio/resources/hvac.rb
hpxml-measures/HPXMLtoOpenStudio/resources/waterheater.rb
hpxml-measures/SimulationOutputReport/measure.rb
hpxml-measures/SimulationOutputReport/measure.xml
hpxml-measures/SimulationOutputReport/tests/output_report_test.rb
hpxml-measures/docs/source/hpxml_to_openstudio.rst
hpxml-measures/docs/source/simulation_output_report.rst
hpxml-measures/workflow/run_simulation.rb

Includes hot water loads (in addition to heating/cooling loads) when timeseries total loads are requested.
Also fixes possible "Error: Electricity category end uses (X) do not sum to total (X)." when the building has a heat pump water heater.

Timeseries hot water loads

---

Changelog.md
docs/source/workflow_inputs.rst
rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
rulesets/301EnergyRatingIndexRuleset/tests/test_hvac.rb
tasks.rb
workflow/sample_files/base-hvac-mini-split-air-conditioner-only-ducted.xml
workflow/sample_files/base-hvac-mini-split-air-conditioner-only-ductless.xml

Add support for mini-split ACs. (Mini-split ACs previously needed to be modeled as mini-split HPs with FractionHeatLoadServed=0.)

Mini-Split Air Conditioners

---

docs/source/workflow_outputs.rst
rulesets/301EnergyRatingIndexRuleset/measure.xml
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
workflow/energy_rating_index.rb

Breaks out EUL_DH/REUL_DH from EUL_LA/REUL_LA in output files. All other changes were already incorporated.

Changes for RESNET 55i

---

workflow/design.rb
workflow/energy_rating_index.rb
workflow/tests/energy_rating_index_test.rb

Skips some internal validation checks.

Speed up simulations

---

docs/source/workflow_inputs.rst

Fixes chiller documentation to remove reference to deprecated `HydronicAndAirDistribution`.

Small fix to chiller documentation

---

Changelog.md
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml

Enclosure elements with very high R-values could result in an error ("Construction R-value ... does not match Assembly R-value"). This fixes it.

High R-value bugfix

---

hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb

- If SystemIdentifier isn't included on an object at all, the check_errors function would crash with a runtime error about reading size of undefined
- This fix makes the useful error print out if the id isn't defined at all, or if the string that is there is empty
This is my first PR into this repo, so please let me know which if any of the steps below I need to do to make this a more complete PR. 

Error Reporting Fix: Allow error reporting to complete without crashing if the system identifier is completely undefined

---

hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hpxml.rb
hpxml-measures/HPXMLtoOpenStudio/tests/test_validation.rb
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/invalid_files/boiler-invalid-afue.xml
hpxml-measures/workflow/sample_files/invalid_files/furnace-invalid-afue.xml
hpxml-measures/workflow/tests/hpxml_translator_test.rb
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
rulesets/301EnergyRatingIndexRuleset/tests/test_validation.rb

Adds error-checking to ensure `HeatingSystem/AnnualHeatingEfficiency/Value` is between 0 and 1 if Units are "AFUE" or "Percent".

Add AFUE/Percent error-checking

---

Changelog.md
docs/source/workflow_inputs.rst
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hvac.rb
hpxml-measures/docs/source/workflow_inputs.rst
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/base-bldgtype-multifamily-shared-ground-loop-ground-to-air-heat-pump.xml
hpxml-measures/workflow/tests/hpxml_translator_test.rb
workflow/sample_files/base-bldgtype-multifamily-shared-ground-loop-ground-to-air-heat-pump.xml

Allow pump powers to be zero, needed for some situations. Clarifies some documentation.

Pump power

---

Changelog.md
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/BaseElements.xsd
hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.xml
hpxml-measures/HPXMLtoOpenStudio/resources/HPXMLDataTypes.xsd
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/base-atticroof-conditioned.xml
hpxml-measures/workflow/tests/hpxml_translator_test.rb
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
workflow/sample_files/base-atticroof-conditioned.xml
workflow/sample_files/base-bldgtype-multifamily-shared-ground-loop-ground-to-air-heat-pump.xml

Relaxes tolerance for duct leakage to outside warning when ducts solely in conditioned space.

Latest OS-HPXML

---

Changelog.md
docs/source/capabilities.rst
docs/source/workflow_outputs.rst
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/constants.rb
hpxml-measures/HPXMLtoOpenStudio/resources/misc_loads.rb
hpxml-measures/SimulationOutputReport/measure.rb
hpxml-measures/SimulationOutputReport/measure.xml
hpxml-measures/docs/source/intro.rst
hpxml-measures/docs/source/workflow_outputs.rst
hpxml-measures/workflow/run_simulation.rb
hpxml-measures/workflow/template.osw
hpxml-measures/workflow/tests/hpxml_translator_test.rb
workflow/design.rb
workflow/energy_rating_index.rb

Adds a `--skip-component-loads` argument to allow skipping the heating/cooling component loads calculation if not of interest. When used, reduces runtime of each simulation by 1-1.5 seconds.

Allow skipping component loads (for faster performance)

---

workflow/tests/energy_rating_index_test.rb

Minor cleanup to HERS tests:
1. Use file name, not full path, in 140 results csv. 
2. Round values for Ref Home Auto Generation csv results to the same number of sig figs as the HERS spreadsheet and use `assert_equal` instead of `assert_in_epsilon`.

Cleanup tests

---

workflow/tests/energy_rating_index_test.rb

Enable --skip-component-loads on CI runs.

---

Changelog.md
docs/source/capabilities.rst
docs/source/workflow_outputs.rst
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.rb
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/SimulationOutputReport/measure.rb
hpxml-measures/SimulationOutputReport/measure.xml
hpxml-measures/docs/source/intro.rst
hpxml-measures/docs/source/workflow_outputs.rst
hpxml-measures/workflow/run_simulation.rb
hpxml-measures/workflow/template.osw
hpxml-measures/workflow/tests/hpxml_translator_test.rb
workflow/design.rb
workflow/energy_rating_index.rb
workflow/tests/energy_rating_index_test.rb

Follow-up to #514.
**Breaking change**: Changes component load calculation to opt-in w/ `--add-component-loads` arguments. (Previously opt-out w/ `--skip-component-loads` argument.)

Opt-in component loads calc

---

Changelog.md
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/EPvalidator.xml
hpxml-measures/HPXMLtoOpenStudio/tests/test_water_heater.rb
hpxml-measures/tasks.rb
hpxml-measures/workflow/sample_files/base-bldgtype-multifamily-shared-laundry-room.xml
hpxml-measures/workflow/sample_files/invalid_files/invalid-facility-type-equipment.xml
hpxml-measures/workflow/sample_files/invalid_files/unattached-shared-clothes-washer-water-heater.xml
hpxml-measures/workflow/sample_files/invalid_files/unattached-shared-dishwasher-water-heater.xml
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
rulesets/301EnergyRatingIndexRuleset/tests/test_water_heating.rb
workflow/sample_files/base-bldgtype-multifamily-shared-laundry-room.xml
workflow/tests/base_results/sample_files.csv
workflow/tests/base_results/sample_files_energystar.csv

Removes limitation that a shared water heater serving a shared laundry room can't also serve dwelling unit fixtures (i.e., `FractionDHWLoadServed` is no longer required to be zero).

Removes shared laundry limitation

---

Changelog.md
docs/source/getting_started.rst
docs/source/workflow_outputs.rst
rulesets/301EnergyRatingIndexRuleset/measure.rb
rulesets/EnergyStarRuleset/measure.xml
rulesets/EnergyStarRuleset/resources/EnergyStarRuleset.rb
rulesets/EnergyStarRuleset/tests/test_es_enclosure.rb
rulesets/EnergyStarRuleset/tests/test_es_ventilation.rb
tasks.rb
workflow/design.rb
workflow/energy_rating_index.rb
workflow/energy_star.rb
workflow/tests/energy_rating_index_test.rb
workflow/util.rb

Allows monthly or daily outputs instead of hourly, if desired. Closes #555.

Allow more timeseries outputs

---

Changelog.md
docs/source/workflow_inputs.rst
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml
rulesets/301EnergyRatingIndexRuleset/tests/test_enclosure.rb
rulesets/EnergyStarRuleset/measure.xml
rulesets/EnergyStarRuleset/resources/EnergyStarRuleset.rb

Allows optional `AirInfiltrationMeasurement/InfiltrationHeight` input. InfiltrationHeight is defined as the vertical distance between the lowest and highest above-grade points within the pressure boundary, per ASHRAE 62.2. If InfiltrationHeight is not provided, it is inferred from other inputs (e.g., conditioned floor area, number of conditioned floors above-grade, above-grade foundation wall height, etc.) as before.

Optional `AirInfiltrationMeasurement/InfiltrationHeight` input

---

Changelog.md
docs/source/workflow_inputs.rst
hpxml-measures/Changelog.md
hpxml-measures/HPXMLtoOpenStudio/measure.xml
hpxml-measures/HPXMLtoOpenStudio/resources/hpxml_schematron/EPvalidator.xml
hpxml-measures/HPXMLtoOpenStudio/tests/test_validation.rb
hpxml-measures/docs/source/workflow_inputs.rst
rulesets/301EnergyRatingIndexRuleset/resources/301validator.xml

Received an HPXML where `AirflowDefectRatio` was set to 99. This is allowed because there is technically no upper limit to how the fraction is calculated. But in practical terms, a home can only be _so_ bad.
This PR adds more stringent limits for `AirflowDefectRatio`: -0.9 to 9, which now allows the measured value to be 1/10th to 10x the design value. This will help ensure that users don't accidentally misinterpret the input (say, as a percentage).

More stringent HVAC Installation Quality limits

---

Changelog.md
docs/source/usage_instructions.rst
workflow/design.rb
workflow/energy_rating_index.rb
workflow/energy_star.rb
workflow/tests/energy_rating_index_test.rb
workflow/tests/energy_star_test.rb
workflow/tests/util.rb
workflow/util.rb

Adds a `--skip-simulation` flag that can be used to just generate the ERI Rated/Reference Home HPXMLs and then stop.
E.g.:
`openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml --skip-simulation`

Adds `--skip-simulation` flag

---

Changelog.md
workflow/util.rb

Fixes possible NaN result for ERI if, in a very cold climate, the Reference Home has no cooling load.

Fixes possible NaN result

---

Changelog.md
workflow/energy_rating_index.rb
workflow/energy_star.rb
workflow/tests/energy_rating_index_test.rb
workflow/tests/util.rb
workflow/util.rb

Adds a `--rated-home-only` flag to run only the ERI Rated Home simulation (ERI will not be calculated).
E.g., `openstudio workflow/energy_rating_index.rb -x workflow/sample_files/base.xml -o test --rated-home-only`

Allow running only the ERI Rated Home

---

Changelog.md
rulesets/301EnergyRatingIndexRuleset/resources/301.rb
workflow/util.rb

Fixes possible error when running HERS Auto-Generation tests.

Auto-Gen bugfix

---

rulesets/301EnergyRatingIndexRuleset/measure.rb
rulesets/EnergyStarRuleset/measure.rb
rulesets/EnergyStarRuleset/measure.xml

Should have some runtime improvement w/o any downside.

Remove redundant HPXML validations

---

Changelog.md
rulesets/main.rb

Fix ERI warnings

---

Changelog.md
rulesets/resources/ES_ZERHruleset.rb
rulesets/tests/test_es_zerh_enclosure.rb

EPA's intention has been that the floor type would be the same construction in the Reference Design as the Rated Home, but the Target Procedure currently says floor construction is wood-framed in the Reference Design. EPA will be updating the Target Procedures to note that the floor construction in the Reference Design should match the Rated Home. 

ENERGY STAR MFNC: Use the same floor construction in Reference Designs as Rated Homes

---

Changelog.md
workflow/energy_rating_index.rb

Fixes possible "Sum of energy consumptions do not match total" error for a shared water heater w/ FractionDHWLoadServed=0 (i.e., it only serves shared hot water appliances).

Fixes possible "Sum of energy consumptions do not match total" error

---

.github/workflows/config.yml

Since sphinx isn't automatically flagging this, manually check for number of footnote references not equal to number of footnotes on the CI.

Docs footnote check

---

Changelog.md
rulesets/main.rb

Fix emissions lookup when zip code starts with a zero

---

Changelog.md
rulesets/resources/hers_diagnostic_output/HERSDiagnosticOutput.schema.json
workflow/design.rb
workflow/energy_rating_index.rb

Adds the `battery_storage` term.

Update to HERS diagnostic output v0.3.0

---

hpxml-measures/HPXMLtoOpenStudio/resources/minitest_helper.rb
workflow/tests/resnet_hers_test.rb
workflow/tests/resnet_other_test.rb
workflow/tests/util.rb

Conditionally check results only when all expected data is available to ensure complete validation. Suppress log warnings related to temporary directory removal to avoid unnecessary test failures.

Add conditional checks and suppress specific log warnings
